---
- hosts: all 
  become: True
  remote_user: tematy.it
#
  tasks:
    - name: Install packages
      apt:
        name: "apache2, nagios4, python3-passlib, monitoring-plugins-contrib, nagios-nrpe-plugin"
        state: "present"
    - name: Start nginx server
      service:
        name: nginx
        state: started
        enabled: True
