---
- hosts: all 
  become: True
  remote_user: tematy.it
#
  tasks:
    - name: Install packages
      apt:
        name: "apache2, nagios4, python3-passlib, monitoring-plugins-contrib, nagios-nrpe-plugin"
        state: "present"
    - name: Start apache2 server
      service:
        name: apache2
        state: started
        enabled: True

    - name: enable apache modules md
      community.general.apache2_module:
        state: present
        name: md
    - name: enable apache modules ssl
      community.general.apache2_module:
        state: present
        name: ssl
    - name: enable apache modules cgi
      community.general.apache2_module:
        state: present
        name: cgi
    - name: enable apache modules headers
      community.general.apache2_module:
        state: present
        name: headers
    - name: Restart apache2 server
      service:
        name: apache2
        state: restarted
    - name: Restart nagios4 server
      service:
        name: nagios4
        state: restarted

#sudo sudo git clone https://github.com/zabawkiadmina/nagios.git
#sudo usermod -a -G nagios www-data
#sudo service apache2 restart
#tematy.it@tematyka1:~/nagios$ sudo systemctl restart nagios4.service



#ansible-playbook -i hosts --limit node1 -u tematy.it main.yml -b -K --ask-pass