---
- hosts: all 
  become: True
  remote_user: tematy.it
#
  tasks:
    - name: Install packages
      apt:
        name: "apache2, nagios4, python3-passlib, monitoring-plugins-contrib, nagios-nrpe-plugin"
        state: "present"
    - name: Start apache2 server
      service:
        name: apache2
        state: started
        enabled: True
#ansible-playbook -i hosts --limit node1 -u tematy.it main.yml -b -K --ask-pass