---
- hosts: all 
  become: True
  remote_user: tematy.it
  vars:
    ansible_become_pass: Warszawa
  tasks:
    - name: Install packages
      apt:
        name: "nginx"
        state: "present"
    - name: Start nginx server
      service:
        name: nginx
        state: started
        enabled: True
    - name: Deploy static website
      copy:
        src: index.html # We have define a html page 
        dest: /var/www/html/
